version: '3.8'

services:
  gpt-api:
    build: .
    container_name: nordflytt-gpt-api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nordflytt-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    container_name: nordflytt-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - gpt-api
    networks:
      - nordflytt-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  nordflytt-network:
    driver: bridge